before:
  hooks:
    - go mod tidy
builds:
  - binary: rsaryev
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: gpt-quiz
    homepage: "https://github.com/rsaryev/gpt-quiz"
    repository:
      owner: rsaryev
      name: gpt-quiz
    commit_author:
      name: rsaryev
      email: rsaryev@yahoo.com

checksum:
  name_template: 'checksums.txt'